export const stationData = {
  /* ========= LINE 1 ========= */

  Vaughan_Metropolitan_Centre_Station: { openingDate: "December 17, 2017", address: "7332 Jane St, Vaughan", linesServed: "Line 1" },
  Highway_407_Station: { openingDate: "December 17, 2017", address: "3150 Highway 7, Vaughan", linesServed: "Line 1" },
  Pioneer_Village_Station: { openingDate: "December 17, 2017", address: "Steeles Ave W & Northwest Gate, Toronto", linesServed: "Line 1" },
  York_University_Station: { openingDate: "December 17, 2017", address: "4700 Keele St, Toronto", linesServed: "Line 1" },
  Finch_West_Station: { openingDate: "December 17, 2017", address: "Yonge St & Finch Ave W, Toronto", linesServed: "Line 1, Line 6" },
  Downsview_Park_Station: { openingDate: "December 17, 2017", address: "70 Canuck Ave, Toronto", linesServed: "Line 1, Downsview Park - Barrie GO" },
  Sheppard_West_Station: { openingDate: "March 31, 1996", address: "75 Billy Bishop Way, Toronto", linesServed: "Line 1" },
  Wilson_Station: { openingDate: "January 28, 1978", address: "570 Wilson Ave, Toronto", linesServed: "Line 1" },
  Yorkdale_Station: { openingDate: "January 28, 1978", address: "1 Yorkdale Rd, Toronto", linesServed: "Line 1" },
  Lawrence_West_Station: { openingDate: "January 28, 1978", address: "655 Lawrence Ave W, Toronto", linesServed: "Line 1" },
  Glencairn_Station: { openingDate: "January 28, 1978", address: "785 Glencairn Ave, Toronto", linesServed: "Line 1" },
  Cedarvale_Station: { openingDate: "January 28, 1978", address: "1300 Eglinton Ave W, Toronto", linesServed: "Line 1, Line 5" },
  St_Clair_West_Station: { openingDate: "January 28, 1978", address: "396 St Clair Ave W, Toronto", linesServed: "Line 1" },
  Dupont_Station: { openingDate: "February 28, 1966", address: "278 Dupont St, Toronto", linesServed: "Line 1" },
  Spadina_Station: { openingDate: "February 28, 1966", address: "285 Spadina Rd, Toronto", linesServed: "Line 1, Line 2" },
  St_George_Station: { openingDate: "February 28, 1966", address: "139 St George St, Toronto", linesServed: "Line 1, Line 2" },
  Museum_Station: { openingDate: "February 28, 1966", address: "75 Queen's Park, Toronto", linesServed: "Line 1" },
  Queens_Park_Station: { openingDate: "February 28, 1966", address: "690 University Ave, Toronto", linesServed: "Line 1" },
  St_Patrick_Station: { openingDate: "February 28, 1966", address: "444 University Ave, Toronto", linesServed: "Line 1" },
  Osgoode_Station: { openingDate: "February 28, 1966", address: "1 University Ave, Toronto", linesServed: "Line 1" },
  St_Andrew_Station: { openingDate: "February 28, 1966", address: "145 King St W, Toronto", linesServed: "Line 1" },
  Union_Station: { openingDate: "March 30, 1954", address: "55 Front St W, Toronto", linesServed: "Line 1, Union - All GO Lines, UP Express, VIA Rail" },
  King_Station: { openingDate: "March 30, 1954", address: "1 King St W, Toronto", linesServed: "Line 1" },
  Queen_Station: { openingDate: "March 30, 1954", address: "2 Queen St E, Toronto", linesServed: "Line 1" },
  Dundas_Station: { openingDate: "March 30, 1954", address: "300 Yonge St, Toronto", linesServed: "Line 1" },
  College_Station: { openingDate: "March 30, 1954", address: "444 Yonge St, Toronto", linesServed: "Line 1" },
  Wellesley_Station: { openingDate: "March 30, 1954", address: "596 Yonge St, Toronto", linesServed: "Line 1" },
  Bloor_Yonge_Station: { openingDate: "March 30, 1954", address: "2 Bloor St E, Toronto", linesServed: "Line 1, Line 2" },
  Rosedale_Station: { openingDate: "February 17, 1954", address: "12 Crescent Rd, Toronto", linesServed: "Line 1" },
  Summerhill_Station: { openingDate: "February 17, 1954", address: "1140 Yonge St, Toronto", linesServed: "Line 1" },
  St_Clair_Station: { openingDate: "February 17, 1954", address: "10 St Clair Ave W, Toronto", linesServed: "Line 1" },
  Davisville_Station: { openingDate: "February 17, 1954", address: "1900 Yonge St, Toronto", linesServed: "Line 1" },
  Eglinton_Station: { openingDate: "March 31, 1954", address: "2200 Yonge St, Toronto", linesServed: "Line 1, Line 5" },
  Lawrence_Station: { openingDate: "January 28, 1978", address: "3100 Yonge St, Toronto", linesServed: "Line 1" },
  York_Mills_Station: { openingDate: "March 31, 1973", address: "4020 Yonge St, Toronto", linesServed: "Line 1" },
  Sheppard_Yonge_Station: { openingDate: "March 31, 1974", address: "4800 Yonge St, Toronto", linesServed: "Line 1, Line 4" },
  North_York_Centre_Station: { openingDate: "June 18, 1987", address: "5150 Yonge St, Toronto", linesServed: "Line 1" },
  Finch_Station: { openingDate: "June 18, 1974", address: "5700 Yonge St, Toronto", linesServed: "Line 1" },

  /* ========= LINE 2 ========= */

  Kipling_Station: { openingDate: "November 22, 1980", address: "27 St Albans Rd, Toronto", linesServed: "Line 2, Kipling - Milton GO" },
  Islington_Station: { openingDate: "November 22, 1968", address: "1226 Islington Ave, Toronto", linesServed: "Line 2" },
  Royal_York_Station: { openingDate: "February 25, 1968", address: "955 Royal York Rd, Toronto", linesServed: "Line 2" },
  Old_Mill_Station: { openingDate: "February 25, 1968", address: "2672 Bloor St W, Toronto", linesServed: "Line 2" },
  Jane_Station: { openingDate: "February 25, 1968", address: "10 Jane St, Toronto", linesServed: "Line 2" },
  Runnymede_Station: { openingDate: "February 25, 1968", address: "2150 Bloor St W, Toronto", linesServed: "Line 2" },
  High_Park_Station: { openingDate: "February 25, 1968", address: "35 Quebec Ave, Toronto", linesServed: "Line 2" },
  Keele_Station: { openingDate: "February 25, 1968", address: "21 Keele St, Toronto", linesServed: "Line 2" },
  Dundas_West_Station: { openingDate: "February 25, 1968", address: "7 Edna Ave, Toronto", linesServed: "Line 2, Bloor - Kitchener GO" },
  Lansdowne_Station: { openingDate: "February 25, 1968", address: "1315 Bloor St W, Toronto", linesServed: "Line 2" },
  Dufferin_Station: { openingDate: "February 25, 1968", address: "1100 Bloor St W, Toronto", linesServed: "Line 2" },
  Ossington_Station: { openingDate: "February 25, 1966", address: "746 Ossington Ave, Toronto", linesServed: "Line 2" },
  Christie_Station: { openingDate: "February 25, 1966", address: "779 Christie St, Toronto", linesServed: "Line 2" },
  Bathurst_Station: { openingDate: "February 25, 1966", address: "511 Bathurst St, Toronto", linesServed: "Line 2" },
  Bay_Station: { openingDate: "February 25, 1966", address: "763 Bay St, Toronto", linesServed: "Line 2" },
  Sherbourne_Station: { openingDate: "February 25, 1966", address: "400 Bloor St E, Toronto", linesServed: "Line 2" },
  Castle_Frank_Station: { openingDate: "February 25, 1966", address: "600 Bloor St E, Toronto", linesServed: "Line 2" },
  Broadview_Station: { openingDate: "February 25, 1966", address: "777 Broadview Ave, Toronto", linesServed: "Line 2" },
  Chester_Station: { openingDate: "February 25, 1966", address: "22 Chester Ave, Toronto", linesServed: "Line 2" },
  Pape_Station: { openingDate: "February 25, 1966", address: "743 Pape Ave, Toronto", linesServed: "Line 2, Ontario Line" },
  Donlands_Station: { openingDate: "February 25, 1966", address: "30 Donlands Ave, Toronto", linesServed: "Line 2" },
  Greenwood_Station: { openingDate: "February 25, 1966", address: "400 Strathmore Blvd, Toronto", linesServed: "Line 2" },
  Coxwell_Station: { openingDate: "February 25, 1966", address: "280 Coxwell Ave, Toronto", linesServed: "Line 2" },
  Woodbine_Station: { openingDate: "February 25, 1966", address: "663 Woodbine Ave, Toronto", linesServed: "Line 2" },
  Main_Street_Station: { openingDate: "May 10, 1968", address: "8 Dawes Rd, Toronto", linesServed: "Line 2, Danforth - Lakeshore East and Stouffville GO" },
  Victoria_Park_Station: { openingDate: "May 10, 1968", address: "777 Victoria Park Ave, Toronto", linesServed: "Line 2" },
  Warden_Station: { openingDate: "May 10, 1968", address: "701 Warden Ave, Toronto", linesServed: "Line 2" },
  Kennedy_Station: { openingDate: "November 21, 1980", address: "2455 Eglinton Ave E, Toronto", linesServed: "Line 2, Line 5, Kennedy - Stouffville GO" },

  /* ========= LINE 4 ========= */

  Bayview_Station: { openingDate: "November 22, 2002", address: "595 Sheppard Ave E, Toronto", linesServed: "Line 4" },
  Bessarion_Station: { openingDate: "November 22, 2002", address: "120 Old Leslie St, Toronto", linesServed: "Line 4" },
  Leslie_Station: { openingDate: "November 22, 2002", address: "2550 Sheppard Ave E, Toronto", linesServed: "Line 4, Oriole - Richmond Hill GO" },
  Don_Mills_Station: { openingDate: "November 22, 2002", address: "1700 Sheppard Ave E, Toronto", linesServed: "Line 4" },

  /* ========= LINE 5 ========= */

  Renforth_Station: { openingDate: "Early 2030s (expected)", address: "Eglinton Ave W & Renforth Dr", linesServed: "Line 5" },
  Martin_Grove_Eglinton_Station: { openingDate: "Early 2030s (expected)", address: "Eglinton Ave W & Martin Grove Rd", linesServed: "Line 5" },
  Kipling_Eglinton_Station: { openingDate: "Early 2030s (expected)", address: "Eglinton Ave W & Kipling Ave", linesServed: "Line 5" },
  Islington_Eglinton_Station: { openingDate: "Early 2030s (expected)", address: "Eglinton Ave W & Islington Ave", linesServed: "Line 5" },
  Royal_York_Eglinton_Station: { openingDate: "Early 2030s (expected)", address: "Eglinton Ave W & Royal York Rd", linesServed: "Line 5" },
  Scarlett_Station: { openingDate: "Early 2030s (expected)", address: "Eglinton Ave W & Scarlett Rd", linesServed: "Line 5" },
  Jane_Eglinton_Station: { openingDate: "Early 2030s (expected)", address: "Eglinton Ave W & Jane St", linesServed: "Line 5" },
  Mount_Dennis_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Weston Rd", linesServed: "Line 5, UP Express, Mount Dennis - Kitchener GO" },
  Keelesdale_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Keele St", linesServed: "Line 5" },
  Caledonia_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Caledonia Rd", linesServed: "Line 5" },
  Fairbank_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Dufferin St", linesServed: "Line 5" },
  Oakwood_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Oakwood Ave", linesServed: "Line 5" },
  Forest_Hill_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Bathurst St", linesServed: "Line 5" },
  Chaplin_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Chaplin Cres", linesServed: "Line 5" },
  Avenue_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Avenue Rd", linesServed: "Line 5" },
  Mount_Pleasant_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Mt Pleasant Rd", linesServed: "Line 5" },
  Leaside_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Bayview Ave", linesServed: "Line 5" },
  Laird_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Laird Dr", linesServed: "Line 5" },
  Sunnybrook_Park_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Leslie St", linesServed: "Line 5" },
  Don_Valley_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Don Mills Rd", linesServed: "Line 5" },
  Aga_Khan_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Don Valley Parkway", linesServed: "Line 5" },
  Wynford_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Wynford Dr", linesServed: "Line 5" },
  Sloane_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Sloane Ave", linesServed: "Line 5" },
  O_Connor_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & O'Connor Dr", linesServed: "Line 5" },
  Pharmacy_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Pharmacy Ave", linesServed: "Line 5" },
  Hakimi_Lebovic_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Lebovic Ave", linesServed: "Line 5" },
  Golden_Mile_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Warden Ave", linesServed: "Line 5" },
  Birchmount_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Birchmount Ave", linesServed: "Line 5" },
  Ionview_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Ionview Rd", linesServed: "Line 5" },

  /* ========= LINE 6 ========= */

  Sentinel_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Sentinel Rd", linesServed: "Line 6" },
  Tobermory_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Tobermory Dr", linesServed: "Line 6" },
  Driftwood_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Driftwood Ave", linesServed: "Line 6" },
  Jane_and_Finch_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Jane St", linesServed: "Line 6" },
  Norfinch_Oakdale_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Norfinch Dr / Oakdale Rd", linesServed: "Line 6" },
  Signet_Arrow_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Signet Dr / Arrow Rd", linesServed: "Line 6" },
  Emery_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Weston Rd", linesServed: "Line 6" },
  Milvan_Rumike_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Milvan Dr / Rumike Rd", linesServed: "Line 6" },
  Duncanwoods_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Duncanwoods Dr", linesServed: "Line 6" },
  Pearldale_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Pearldale Ave", linesServed: "Line 6" },
  Rowntree_Mills_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Islington Ave", linesServed: "Line 6" },
  Mount_Olive_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Kipling Ave", linesServed: "Line 6" },
  Stevenson_Station: { openingDate: "December 7, 2025", address: "Finch Ave W adjacent to Stevenson Rd", linesServed: "Line 6" },
  Albion_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Albion Rd", linesServed: "Line 6" },
  Martin_Grove_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Martin Grove Rd", linesServed: "Line 6" },
  Westmore_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Westmore Dr", linesServed: "Line 6" },
  Humber_College_Station: { openingDate: "December 7, 2025", address: "205 Humber College Blvd", linesServed: "Line 6" },

  /* ========= ONTARIO LINE ========= */

  Exhibition_Station: { openingDate: "Early 2030s (expected)", address: "", linesServed: "Ontario Line" },
  King_West_Station: { openingDate: "Early 2030s (expected)", address: "", linesServed: "Ontario Line" },
  Chinatown_Station: { openingDate: "Early 2030s (expected)", address: "", linesServed: "Ontario Line" },
  Moss_Park_Station: { openingDate: "Early 2030s (expected)", address: "", linesServed: "Ontario Line" },
  Distillery_District_Station: { openingDate: "Early 2030s (expected)", address: "", linesServed: "Ontario Line" },
  East_Harbour_Station: { openingDate: "Early 2030s (expected)", address: "", linesServed: "Ontario Line" },
  Leslieville_Station: { openingDate: "Early 2030s (expected)", address: "", linesServed: "Ontario Line" },
  Gerrard_Station: { openingDate: "Early 2030s (expected)", address: "", linesServed: "Ontario Line" },
  Cosburn_Station: { openingDate: "Early 2030s (expected)", address: "", linesServed: "Ontario Line" },
  Thorncliffe_Park_Station: { openingDate: "Early 2030s (expected)", address: "", linesServed: "Ontario Line" },
  Flemingdon_Park_Station: { openingDate: "Early 2030s (expected)", address: "", linesServed: "Ontario Line" },
};