export const stationData = {
  /* ========= LINE 1 ========= */

  Vaughan_Metropolitan_Centre_Station: { openingDate: "December 15, 2017", address: "Jane St & Hwy 7", linesServed: "Line 1" },
  Highway_407_Station: { openingDate: "December 15, 2017", address: "Jane St & Hwy 407", linesServed: "Line 1" },
  Pioneer_Village_Station: { openingDate: "December 15, 2017", address: "Steeles Ave W & Northwest Gate", linesServed: "Line 1" },
  York_University_Station: { openingDate: "December 15, 2017", address: "Ian MacDonald Blvd & York Blvd", linesServed: "Line 1" },
  Finch_West_Station: { openingDate: "December 15, 2017", address: "Keele St & Finch Ave W", linesServed: "Line 1, Line 6" },
  Downsview_Park_Station: { openingDate: "December 15, 2017", address: "Sheppard Ave W & Bakersfield St", linesServed: "Line 1, Downsview Park - Barrie GO" },
  Sheppard_West_Station: { openingDate: "March 31, 1996", address: "Sheppard Ave W & William R. Allen Rd", linesServed: "Line 1" },
  Wilson_Station: { openingDate: "January 27, 1978", address: "William R. Allen Rd & Wilson Ave", linesServed: "Line 1" },
  Yorkdale_Station: { openingDate: "January 27, 1978", address: "William R. Allen Rd & Yorkdale Rd", linesServed: "Line 1" },
  Lawrence_West_Station: { openingDate: "January 27, 1978", address: "William R. Allen Rd & Lawrence Ave W", linesServed: "Line 1" },
  Glencairn_Station: { openingDate: "January 27, 1978", address: "William R. Allen Rd & Glencairn Ave", linesServed: "Line 1" },
  Cedarvale_Station: { openingDate: "January 27, 1978", address: "William R. Allen Rd & Eglinton Ave W", linesServed: "Line 1, Line 5" },
  St_Clair_West_Station: { openingDate: "January 27, 1978", address: "St Clair Ave W & Wells Hill Ave", linesServed: "Line 1" },
  Dupont_Station: { openingDate: "January 27, 1978", address: "Spadina Rd & Dupont St", linesServed: "Line 1" },
  Spadina_Station: { openingDate: "February 25, 1966", address: "Spadina Rd & Bloor St W", linesServed: "Line 1, Line 2" },
  St_George_Station: { openingDate: "February 28, 1963", address: "St George St & Bloor St W", linesServed: "Line 1, Line 2" },
  Museum_Station: { openingDate: "February 28, 1963", address: "Queens Park & Bloor St W", linesServed: "Line 1" },
  Queens_Park_Station: { openingDate: "February 28, 1963", address: "College St & University Ave", linesServed: "Line 1" },
  St_Patrick_Station: { openingDate: "February 28, 1963", address: "Dundas St W & University Ave", linesServed: "Line 1" },
  Osgoode_Station: { openingDate: "February 28, 1963", address: "Queen St W & University Ave", linesServed: "Line 1" },
  St_Andrew_Station: { openingDate: "February 28, 1963", address: "King St W & University Ave", linesServed: "Line 1" },
  Union_Station: { openingDate: "March 30, 1954", address: "Front St W & Bay St", linesServed: "Line 1, Union - All GO Lines, UP Express, VIA Rail" },
  King_Station: { openingDate: "March 30, 1954", address: "King St & Yonge St", linesServed: "Line 1" },
  Queen_Station: { openingDate: "March 30, 1954", address: "Queen St & Yonge St", linesServed: "Line 1" },
  Dundas_Station: { openingDate: "March 30, 1954", address: "Dundas St & Yonge St", linesServed: "Line 1" },
  College_Station: { openingDate: "March 30, 1954", address: "College St & Yonge St", linesServed: "Line 1" },
  Wellesley_Station: { openingDate: "March 30, 1954", address: "Wellesley St & Yonge St", linesServed: "Line 1" },
  Bloor_Yonge_Station: { openingDate: "March 30, 1954", address: "Bloor St & Yonge St", linesServed: "Line 1, Line 2" },
  Rosedale_Station: { openingDate: "March 30, 1954", address: "Crescent Rd & Yonge St", linesServed: "Line 1" },
  Summerhill_Station: { openingDate: "March 30, 1954", address: "Summerhill Ave & Yonge St", linesServed: "Line 1" },
  St_Clair_Station: { openingDate: "March 30, 1954", address: "St Clair Ave & Yonge St", linesServed: "Line 1" },
  Davisville_Station: { openingDate: "March 30, 1954", address: "Davisville Ave & Yonge St", linesServed: "Line 1" },
  Eglinton_Station: { openingDate: "March 30, 1954", address: "Eglinton Ave & Yonge St", linesServed: "Line 1, Line 5" },
  Lawrence_Station: { openingDate: "March 30, 1973", address: "Lawrence Ave & Yonge St", linesServed: "Line 1" },
  York_Mills_Station: { openingDate: "March 30, 1973", address: "York Mills Rd & Yonge St", linesServed: "Line 1" },
  Sheppard_Yonge_Station: { openingDate: "March 29, 1974", address: "Sheppard Ave & Yonge St", linesServed: "Line 1, Line 4" },
  North_York_Centre_Station: { openingDate: "June 18, 1987", address: "Empress Ave & Yonge St", linesServed: "Line 1" },
  Finch_Station: { openingDate: "March 29, 1974", address: "Finch Ave & Yonge St", linesServed: "Line 1" },
  Steeles_Station: { openingDate: "Under Construction", address: "Steeles Ave & Yonge St", linesServed: "Line 1" },
  Clark_Station: { openingDate: "Under Construction", address: "Clark Ave & Yonge St", linesServed: "Line 1" },
  Royal_Orchard_Station: { openingDate: "Under Construction", address: "Royal Orchard Blvd & Yonge St", linesServed: "Line 1" },
  Bridge_Station: { openingDate: "Under Construction", address: "Hwy 7 & Yonge St", linesServed: "Line 1, Langstaff - Richmond Hill GO" },
  High_Tech_Station: { openingDate: "Under Construction", address: "High Tech Rd & Yonge St", linesServed: "Line 1" },

  /* ========= LINE 2 ========= */

  Kipling_Station: { openingDate: "November 21, 1980", address: "Kipling Ave & Dundas St W", linesServed: "Line 2, Kipling - Milton GO" },
  Islington_Station: { openingDate: "May 10, 1968", address: "Islington Ave & Bloor St W", linesServed: "Line 2" },
  Royal_York_Station: { openingDate: "May 10, 1968", address: "Royal York Rd & Bloor St W", linesServed: "Line 2" },
  Old_Mill_Station: { openingDate: "May 10, 1968", address: "Old Mill Trail & Bloor St W", linesServed: "Line 2" },
  Jane_Station: { openingDate: "May 10, 1968", address: "Jane St & Bloor St W", linesServed: "Line 2" },
  Runnymede_Station: { openingDate: "May 10, 1968", address: "Runnymede Rd & Bloor St W", linesServed: "Line 2" },
  High_Park_Station: { openingDate: "May 10, 1968", address: "High Park Ave & Bloor St W", linesServed: "Line 2" },
  Keele_Station: { openingDate: "February 25, 1966", address: "Keele St & Bloor St W", linesServed: "Line 2" },
  Dundas_West_Station: { openingDate: "February 25, 1966", address: "Dundas St W & Bloor St W", linesServed: "Line 2, Bloor - Kitchener GO" },
  Lansdowne_Station: { openingDate: "February 25, 1966", address: "Lansdowne Ave & Bloor St W", linesServed: "Line 2" },
  Dufferin_Station: { openingDate: "February 25, 1966", address: "Dufferin St & Bloor St W", linesServed: "Line 2" },
  Ossington_Station: { openingDate: "February 25, 1966", address: "Ossington Ave & Bloor St W", linesServed: "Line 2" },
  Christie_Station: { openingDate: "February 25, 1966", address: "Christie St & Bloor St W", linesServed: "Line 2" },
  Bathurst_Station: { openingDate: "February 25, 1966", address: "Bathurst St & Bloor St W", linesServed: "Line 2" },
  Bay_Station: { openingDate: "February 25, 1966", address: "Bay St & Bloor St W", linesServed: "Line 2" },
  Sherbourne_Station: { openingDate: "February 25, 1966", address: "Sherbourne St & Bloor St E", linesServed: "Line 2" },
  Castle_Frank_Station: { openingDate: "February 25, 1966", address: "Castle Frank Rd & Bloor St E", linesServed: "Line 2" },
  Broadview_Station: { openingDate: "February 25, 1966", address: "Broadview Ave & Danforth Ave", linesServed: "Line 2" },
  Chester_Station: { openingDate: "February 25, 1966", address: "Chester Ave & Danforth Ave", linesServed: "Line 2" },
  Pape_Station: { openingDate: "February 25, 1966", address: "Pape Ave & Danforth Ave", linesServed: "Line 2, Ontario Line" },
  Donlands_Station: { openingDate: "February 25, 1966", address: "Donlands Ave & Danforth Ave", linesServed: "Line 2" },
  Greenwood_Station: { openingDate: "February 25, 1966", address: "Greenwood Ave & Danforth Ave", linesServed: "Line 2" },
  Coxwell_Station: { openingDate: "February 25, 1966", address: "Coxwell Ave & Danforth Ave", linesServed: "Line 2" },
  Woodbine_Station: { openingDate: "February 25, 1966", address: "Woodbine Ave & Danforth Ave", linesServed: "Line 2" },
  Main_Street_Station: { openingDate: "May 10, 1968", address: "Main St & Danforth Ave", linesServed: "Line 2, Danforth - Lakeshore East and Stouffville GO" },
  Victoria_Park_Station: { openingDate: "May 10, 1968", address: "Victoria Park Ave & Danforth Ave", linesServed: "Line 2" },
  Warden_Station: { openingDate: "May 10, 1968", address: "Warden Ave & St Clair Ave E", linesServed: "Line 2" },
  Kennedy_Station: { openingDate: "November 21, 1980", address: "Kennedy Rd & Eglinton Ave E", linesServed: "Line 2, Line 5, Kennedy - Stouffville GO" },
  Lawrence_East_Station: { openingDate: "Under Construction", address: "Lawrence Ave E & McCowan Rd", linesServed: "Line 2" },
  Scarborough_Centre_Station: { openingDate: "Under Construction", address: "Ellesmere Rd & McCowan Rd", linesServed: "Line 2" },
  Sheppard_McCowan_Station: { openingDate: "Under Construction", address: "Sheppard Ave E & McCowan Rd", linesServed: "Line 2" },

  /* ========= LINE 4 ========= */

  Bayview_Station: { openingDate: "November 22, 2002", address: "Bayview Ave & Sheppard Ave E", linesServed: "Line 4" },
  Bessarion_Station: { openingDate: "November 22, 2002", address: "Bessarion Rd & Sheppard Ave E", linesServed: "Line 4" },
  Leslie_Station: { openingDate: "November 22, 2002", address: "Leslie St & Sheppard Ave E", linesServed: "Line 4, Oriole - Richmond Hill GO" },
  Don_Mills_Station: { openingDate: "November 22, 2002", address: "Don Mills Rd & Sheppard Ave E", linesServed: "Line 4" },

  /* ========= LINE 5 ========= */

  Renforth_Station: { openingDate: "Early 2030s (expected)", address: "Eglinton Ave W & Renforth Dr", linesServed: "Line 5" },
  Martin_Grove_Eglinton_Station: { openingDate: "Early 2030s (expected)", address: "Eglinton Ave W & Martin Grove Rd", linesServed: "Line 5" },
  Kipling_Eglinton_Station: { openingDate: "Early 2030s (expected)", address: "Eglinton Ave W & Kipling Ave", linesServed: "Line 5" },
  Islington_Eglinton_Station: { openingDate: "Early 2030s (expected)", address: "Eglinton Ave W & Islington Ave", linesServed: "Line 5" },
  Royal_York_Eglinton_Station: { openingDate: "Early 2030s (expected)", address: "Eglinton Ave W & Royal York Rd", linesServed: "Line 5" },
  Scarlett_Station: { openingDate: "Early 2030s (expected)", address: "Eglinton Ave W & Scarlett Rd", linesServed: "Line 5" },
  Jane_Eglinton_Station: { openingDate: "Early 2030s (expected)", address: "Eglinton Ave W & Jane St", linesServed: "Line 5" },
  Mount_Dennis_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Weston Rd", linesServed: "Line 5, UP Express, Mount Dennis - Kitchener GO" },
  Keelesdale_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Keele St", linesServed: "Line 5" },
  Caledonia_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Caledonia Rd", linesServed: "Line 5" },
  Fairbank_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Dufferin St", linesServed: "Line 5" },
  Oakwood_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Oakwood Ave", linesServed: "Line 5" },
  Forest_Hill_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Bathurst St", linesServed: "Line 5" },
  Chaplin_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Chaplin Cres", linesServed: "Line 5" },
  Avenue_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave W & Avenue Rd", linesServed: "Line 5" },
  Mount_Pleasant_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Mt Pleasant Rd", linesServed: "Line 5" },
  Leaside_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Bayview Ave", linesServed: "Line 5" },
  Laird_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Laird Dr", linesServed: "Line 5" },
  Sunnybrook_Park_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Leslie St", linesServed: "Line 5" },
  Don_Valley_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Don Mills Rd", linesServed: "Line 5" },
  Aga_Khan_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Don Valley Parkway", linesServed: "Line 5" },
  Wynford_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Wynford Dr", linesServed: "Line 5" },
  Sloane_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Sloane Ave", linesServed: "Line 5" },
  O_Connor_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & O'Connor Dr", linesServed: "Line 5" },
  Pharmacy_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Pharmacy Ave", linesServed: "Line 5" },
  Hakimi_Lebovic_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Lebovic Ave", linesServed: "Line 5" },
  Golden_Mile_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Warden Ave", linesServed: "Line 5" },
  Birchmount_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Birchmount Ave", linesServed: "Line 5" },
  Ionview_Station: { openingDate: "February 8, 2026", address: "Eglinton Ave E & Ionview Rd", linesServed: "Line 5" },

  /* ========= LINE 6 ========= */

  Sentinel_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Sentinel Rd", linesServed: "Line 6" },
  Tobermory_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Tobermory Dr", linesServed: "Line 6" },
  Driftwood_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Driftwood Ave", linesServed: "Line 6" },
  Jane_and_Finch_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Jane St", linesServed: "Line 6" },
  Norfinch_Oakdale_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Norfinch Dr / Oakdale Rd", linesServed: "Line 6" },
  Signet_Arrow_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Signet Dr / Arrow Rd", linesServed: "Line 6" },
  Emery_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Weston Rd", linesServed: "Line 6" },
  Milvan_Rumike_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Milvan Dr / Rumike Rd", linesServed: "Line 6" },
  Duncanwoods_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Duncanwoods Dr", linesServed: "Line 6" },
  Pearldale_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Pearldale Ave", linesServed: "Line 6" },
  Rowntree_Mills_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Islington Ave", linesServed: "Line 6" },
  Mount_Olive_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Kipling Ave", linesServed: "Line 6" },
  Stevenson_Station: { openingDate: "December 7, 2025", address: "Finch Ave W adjacent to Stevenson Rd", linesServed: "Line 6" },
  Albion_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Albion Rd", linesServed: "Line 6" },
  Martin_Grove_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Martin Grove Rd", linesServed: "Line 6" },
  Westmore_Station: { openingDate: "December 7, 2025", address: "Finch Ave W & Westmore Dr", linesServed: "Line 6" },
  Humber_College_Station: { openingDate: "December 7, 2025", address: "Humber College Blvd & Hwy 27", linesServed: "Line 6" },

  /* ========= ONTARIO LINE ========= */

  Exhibition_Station: { openingDate: "Early 2030s (expected)", address: "Manitoba Dr & Nova Scotia Ave", linesServed: "Ontario Line" },
  King_West_Station: { openingDate: "Early 2030s (expected)", address: "King St W & Bathurst St", linesServed: "Ontario Line" },
  Chinatown_Station: { openingDate: "Early 2030s (expected)", address: "Spadina Ave & Queen St W", linesServed: "Ontario Line" },
  Moss_Park_Station: { openingDate: "Early 2030s (expected)", address: "Sherbourne St & Queen St E", linesServed: "Ontario Line" },
  Distillery_District_Station: { openingDate: "Early 2030s (expected)", address: "King St E & Parliament St", linesServed: "Ontario Line" },
  East_Harbour_Station: { openingDate: "Early 2030s (expected)", address: "Broadview Ave & Eastern Ave", linesServed: "Ontario Line" },
  Leslieville_Station: { openingDate: "Early 2030s (expected)", address: "Queen St E & Empire Dr", linesServed: "Ontario Line" },
  Gerrard_Station: { openingDate: "Early 2030s (expected)", address: "Gerrard Ave & Pape Ave", linesServed: "Ontario Line" },
  Cosburn_Station: { openingDate: "Early 2030s (expected)", address: "Cosburn Ave & Pape Ave", linesServed: "Ontario Line" },
  Thorncliffe_Park_Station: { openingDate: "Early 2030s (expected)", address: "Thorncliffe Park Dr & Overlea Blvd", linesServed: "Ontario Line" },
  Flemingdon_Park_Station: { openingDate: "Early 2030s (expected)", address: "Gateway Blvd & Don Mills Rd", linesServed: "Ontario Line" },
};